import React from "react";
import Head from "next/head";
import Image from "next/image";
import avatar from "../assets/me_avatar_3.png";

function About() {
  return (
    <>
      <Head>
        <title>PayneDevHaus_blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/avatar-favicon.ico" />
      </Head>
      <div className="mt-8">
        <div className="h-full">
          <div className="flex justify-center w-full items-center">
            <Image src={avatar} />
          </div>
          <div className="w-[80%] flex flex-col justify-center items-center mx-auto">
            <h1 className="text-4xl text-center mb-12 mt-4">Hey There!</h1>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis
              delectus animi sunt sint debitis placeat atque, quia iure
              accusamus dolor fugiat natus necessitatibus tempore magni rem
              error impedit in! Iusto, fugiat odit blanditiis animi maiores nam
              optio necessitatibus consequuntur vitae velit illo magnam eum
              harum alias inventore ad? Modi cum assumenda sint reprehenderit
              eveniet. Animi ducimus ullam, magni, aliquid rerum temporibus quae
              autem laborum tenetur a assumenda iure maiores culpa nam quos eos
              illo minus error? Voluptas culpa corporis consequatur veritatis,
              quasi odio aliquid in ut earum impedit! Sequi fuga dolorum
              dignissimos labore quo soluta natus repudiandae tempora sunt,
              pariatur optio debitis, autem et est culpa, ullam inventore
              blanditiis! Incidunt repellendus quo voluptates, delectus atque
              praesentium debitis voluptatem blanditiis? Doloremque rem fuga
              provident quaerat reprehenderit quis ducimus nostrum libero?
              Aperiam repudiandae hic expedita mollitia iusto eius accusamus eos
              quaerat. Repellendus nesciunt magni tempora assumenda tempore
              consequuntur quisquam molestiae sed adipisci dolore esse incidunt
              a, quasi ex numquam iste minima quas autem maxime obcaecati modi,
              ab fugit odio. Nulla provident eaque, saepe deleniti, illum optio
              reiciendis, atque totam voluptate quasi fuga at quae quas?
              Pariatur quo quae aspernatur qui non quos impedit, explicabo
              exercitationem harum vitae libero totam numquam consequatur sed?
            </p>
          </div>
        </div>
      </div>
    </>
  );
}

export default About;
