import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "@/components/BlogCard";
import Quote from "@/components/Quote";

const graphcms = new GraphQLClient(
  "https://api-ap-northeast-1.hygraph.com/v2/cle73oo220e3i01t6dfr58rbz/master"
);

const QUERY = gql`
  {
    posts {
      id
      title
      description
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <div className="">
      <Head>
        <title>PayneDevHaus_blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/avatar-favicon.ico" />
      </Head>
      <Quote />
      {/* <div className="w-[90%] mx-auto mt-2">
        <h1 className="text-3xl text-center my-8 font-mono mx-2">
          Life is a Journey.
        </h1>
      </div> */}

      <main className={styles.main}>
        {posts
          .sort((a, b) => {
            return new Date(b.datePublished) - new Date(a.datePublished);
          })
          .map((post) => (
            <BlogCard
              title={post.title}
              author={post.author}
              description={post.description}
              coverPhoto={post.coverPhoto}
              key={post.id}
              datePublished={post.datePublished}
              slug={post.slug}
            />
          ))}
      </main>
    </div>
  );
}
